In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Retail_Dataset_Cleaned.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

Display First Five Records

In [3]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

Check Dataset Information

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
dtypes: float64(15), int64(10), object(22)
memory usage: 1.8+ MB

Calculate Mean Revenue

In [5]:
mean_revenue = df["Revenue"].mean()

print("Mean Revenue:", mean_revenue)

Mean Revenue: 1392167.3212313203

Calculate Median Revenue

In [6]:
median_revenue = df["Revenue"].median()

print("Median Revenue:", median_revenue)

Median Revenue: 376096.0

Compare Mean and Median

In [10]:
comparison = pd.DataFrame({
    "Statistic": ["Mean Revenue", "Median Revenue"],
    "Value": [mean_revenue, median_revenue]
})

comparison

        Statistic         Value
0    Mean Revenue  1.392167e+06
1  Median Revenue  3.760960e+05

Calculate Mean Units Sold

In [11]:
mean_units = df["Units_Sold"].mean()

print("Average Units Sold:", mean_units)

Average Units Sold: 44.40698540445827

Calculate Median Delivery Time

In [12]:
median_delivery = df["Delivery_Time"].median()

print("Median Delivery Time:", median_delivery)

Median Delivery Time: 4.0

Calculate Mode Product Category

In [14]:
mode_category = df["Category"].mode()

print("Most Common Product Category:")
print(mode_category)

Most Common Product Category:
0    Electronics
Name: Category, dtype: object

Display Statistical Results

In [16]:
print("Mean Revenue:", mean_revenue)
print("Median Revenue:", median_revenue)

Mean Revenue: 1392167.3212313203
Median Revenue: 376096.0

**Task 2: Statistical Summaries**

Generate Summary Statistics

In [17]:
df.describe()

,Quantity_Available,Units_Sold,Unit_Price,Cost_Price,Revenue,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,...,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Shipping_Cost,Month,Year
count,5146.000000,5146.000000,5146.000000,5146.000000,5.146000e+03,5146.000000,5146.000000,5146.000000,5146.000000,5146.000000,...,5146.000000,5146.000000,5146.000000,5146.000000,5146.000000,5146.000000,5146.000000,5146.000000,5146.000000,5146.000000
mean,148.711660,44.406985,36200.123202,28052.458414,1.392167e+06,22.448311,45071.163817,3.925367,142.801982,20.983463,...,5.544695,4.248543,15.403964,16.222114,81.341333,80.298387,3.986027,163.771017,6.570735,2023.017101
std,60.791987,26.897610,53995.455582,41916.676567,2.383555e+06,4.346833,67513.033478,2.281656,128.355595,12.221595,...,2.863402,0.433526,6.013793,6.649421,8.014005,8.542020,2.011049,134.628786,3.464123,0.814172
min,14.000000,4.000000,36.000000,28.000000,8.400000e+02,14.680000,41.000000,0.300000,32.000000,0.000000,...,1.000000,3.500000,3.000000,3.000000,67.000000,60.000000,1.000000,50.000000,1.000000,2022.000000
25%,100.000000,25.000000,2019.500000,1553.250000,5.184600e+04,18.670000,2492.000000,2.220000,68.000000,13.100000,...,3.000000,3.900000,11.300000,11.000000,75.900000,77.700000,2.000000,89.000000,4.000000,2022.000000
50%,149.000000,40.000000,11825.500000,9174.500000,3.760960e+05,22.430000,14820.500000,3.440000,105.000000,22.300000,...,6.000000,4.200000,14.900000,18.000000,80.300000,83.000000,4.000000,123.000000,7.000000,2023.000000
75%,195.000000,59.000000,53814.000000,41569.500000,1.770355e+06,26.220000,66770.000000,5.260000,162.000000,31.200000,...,8.000000,4.600000,18.900000,22.000000,84.600000,86.600000,6.000000,178.000000,10.000000,2024.000000
max,337.000000,154.000000,307651.000000,252171.000000,2.334358e+07,30.430000,450890.000000,11.100000,1200.000000,40.000000,...,10.000000,5.000000,30.000000,25.000000,100.000000,90.000000,7.000000,799.000000,12.000000,2024.000000

Summary of Revenue and Profit Margin

In [18]:
df[[
    "Revenue",
    "Profit_Margin"
]].describe()

            Revenue  Profit_Margin
count  5.146000e+03    5146.000000
mean   1.392167e+06      22.448311
std    2.383555e+06       4.346833
min    8.400000e+02      14.680000
25%    5.184600e+04      18.670000
50%    3.760960e+05      22.430000
75%    1.770355e+06      26.220000
max    2.334358e+07      30.430000

Summary of Inventory Data

In [21]:
df[[
    "Quantity_Available",
    "Units_Sold"
]].describe()

       Quantity_Available   Units_Sold
count         5146.000000  5146.000000
mean           148.711660    44.406985
std             60.791987    26.897610
min             14.000000     4.000000
25%            100.000000    25.000000
50%            149.000000    40.000000
75%            195.000000    59.000000
max            337.000000   154.000000

Summary of Customer Satisfaction

In [22]:
df[[
    "Customer_Satisfaction"
]].describe()

       Customer_Satisfaction
count            5146.000000
mean                4.209328
std                 0.278629
min                 3.600000
25%                 4.000000
50%                 4.200000
75%                 4.400000
max                 4.900000

Generate Summary for All Columns

In [23]:
df.describe(include="all")

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
count,5146,5146,5146,5146,5146,5146,5146,5146,5146,5146,...,5146.000000,5146.000000,5146,5146,5146.000000,5146.000000,5146.000000,5146.000000,5146,5146
unique,1179,280,4,5,51,3,53,20,25,5,...,NaN,NaN,3,3,NaN,NaN,NaN,NaN,4,4
top,BX_DELHI_092,BrandX_India Gadget Zone Delhi,BrandX_India,Mall Store,Delhi,Metro,H&M Cotton Tee,Electronics,T-Shirts,Growing,...,NaN,NaN,Competitive,Low,NaN,NaN,NaN,NaN,Q4,Monsoon
freq,20,77,5085,1059,1087,3559,208,1290,359,1092,...,NaN,NaN,2069,3739,NaN,NaN,NaN,NaN,1326,1710
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.341333,80.298387,NaN,NaN,3.986027,163.771017,6.570735,2023.017101,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.014005,8.542020,NaN,NaN,2.011049,134.628786,3.464123,0.814172,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.000000,60.000000,NaN,NaN,1.000000,50.000000,1.000000,2022.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.900000,77.700000,NaN,NaN,2.000000,89.000000,4.000000,2022.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.300000,83.000000,NaN,NaN,4.000000,123.000000,7.000000,2023.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84.600000,86.600000,NaN,NaN,6.000000,178.000000,10.000000,2024.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,90.000000,NaN,NaN,7.000000,799.000000,12.000000,2024.000000,NaN,NaN

Calculate Range of Revenue

In [24]:
revenue_range = (
    df["Revenue"].max() -
    df["Revenue"].min()
)

print("Revenue Range:", revenue_range)

Revenue Range: 23342742.0

Calculate Standard Deviation of Revenue

In [25]:
revenue_std = df["Revenue"].std()

print("Revenue Standard Deviation:", revenue_std)

Revenue Standard Deviation: 2383554.710861319

Calculate Variance of Revenue

In [26]:
revenue_variance = df["Revenue"].var()

print("Revenue Variance:", revenue_variance)

Revenue Variance: 5681333059669.1875

Create Summary Table

In [27]:
summary_table = pd.DataFrame({
    "Statistic": [
        "Mean Revenue",
        "Median Revenue",
        "Revenue Std Dev",
        "Revenue Variance"
    ],
    "Value": [
        df["Revenue"].mean(),
        df["Revenue"].median(),
        df["Revenue"].std(),
        df["Revenue"].var()
    ]
})

summary_table

          Statistic         Value
0      Mean Revenue  1.392167e+06
1    Median Revenue  3.760960e+05
2   Revenue Std Dev  2.383555e+06
3  Revenue Variance  5.681333e+12

Verify Dataset Information

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
dtypes: float64(15), int64(10), object(22)
memory usage: 1.8+ MB